=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class AuditLogExtensionPluginUpdatedMetadataV2 < ApiModelBase
    # Whether the plugin is mounted into agent runs after the change (true, false)
    attr_accessor :after_enabled

    # How many skills are selected after the change, absent when every skill loads
    attr_accessor :after_enabled_skill_count

    # The plugin's name after the change
    attr_accessor :after_name

    # The source control provider of the plugin's new repository (github, gitlab)
    attr_accessor :after_provider

    # The name of the plugin's new repository
    attr_accessor :after_repo_name

    # The owner of the plugin's new repository
    attr_accessor :after_repo_owner

    # Which skills load after the change: every skill, or only the selected ones (automatic, selected)
    attr_accessor :after_skill_selection_mode

    # The plugin's new directory within its repository, absent when it is the repository root
    attr_accessor :after_subpath

    # Whether the plugin was mounted into agent runs before the change (true, false)
    attr_accessor :before_enabled

    # How many skills were selected before the change, absent when every skill loaded
    attr_accessor :before_enabled_skill_count

    # The plugin's name before the change
    attr_accessor :before_name

    # The source control provider of the plugin's previous repository (github, gitlab)
    attr_accessor :before_provider

    # The name of the plugin's previous repository
    attr_accessor :before_repo_name

    # The owner of the plugin's previous repository
    attr_accessor :before_repo_owner

    # Which skills loaded before the change: every skill, or only the selected ones (automatic, selected)
    attr_accessor :before_skill_selection_mode

    # The plugin's previous directory within its repository, absent when it was the repository root
    attr_accessor :before_subpath

    # What the update changed, comma separated (enabled, skill_selection, name, location)
    attr_accessor :changed

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'after_enabled' => :'after_enabled',
        :'after_enabled_skill_count' => :'after_enabled_skill_count',
        :'after_name' => :'after_name',
        :'after_provider' => :'after_provider',
        :'after_repo_name' => :'after_repo_name',
        :'after_repo_owner' => :'after_repo_owner',
        :'after_skill_selection_mode' => :'after_skill_selection_mode',
        :'after_subpath' => :'after_subpath',
        :'before_enabled' => :'before_enabled',
        :'before_enabled_skill_count' => :'before_enabled_skill_count',
        :'before_name' => :'before_name',
        :'before_provider' => :'before_provider',
        :'before_repo_name' => :'before_repo_name',
        :'before_repo_owner' => :'before_repo_owner',
        :'before_skill_selection_mode' => :'before_skill_selection_mode',
        :'before_subpath' => :'before_subpath',
        :'changed' => :'changed'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'after_enabled' => :'String',
        :'after_enabled_skill_count' => :'String',
        :'after_name' => :'String',
        :'after_provider' => :'String',
        :'after_repo_name' => :'String',
        :'after_repo_owner' => :'String',
        :'after_skill_selection_mode' => :'String',
        :'after_subpath' => :'String',
        :'before_enabled' => :'String',
        :'before_enabled_skill_count' => :'String',
        :'before_name' => :'String',
        :'before_provider' => :'String',
        :'before_repo_name' => :'String',
        :'before_repo_owner' => :'String',
        :'before_skill_selection_mode' => :'String',
        :'before_subpath' => :'String',
        :'changed' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::AuditLogExtensionPluginUpdatedMetadataV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::AuditLogExtensionPluginUpdatedMetadataV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'after_enabled')
        self.after_enabled = attributes[:'after_enabled']
      end

      if attributes.key?(:'after_enabled_skill_count')
        self.after_enabled_skill_count = attributes[:'after_enabled_skill_count']
      end

      if attributes.key?(:'after_name')
        self.after_name = attributes[:'after_name']
      end

      if attributes.key?(:'after_provider')
        self.after_provider = attributes[:'after_provider']
      end

      if attributes.key?(:'after_repo_name')
        self.after_repo_name = attributes[:'after_repo_name']
      end

      if attributes.key?(:'after_repo_owner')
        self.after_repo_owner = attributes[:'after_repo_owner']
      end

      if attributes.key?(:'after_skill_selection_mode')
        self.after_skill_selection_mode = attributes[:'after_skill_selection_mode']
      end

      if attributes.key?(:'after_subpath')
        self.after_subpath = attributes[:'after_subpath']
      end

      if attributes.key?(:'before_enabled')
        self.before_enabled = attributes[:'before_enabled']
      end

      if attributes.key?(:'before_enabled_skill_count')
        self.before_enabled_skill_count = attributes[:'before_enabled_skill_count']
      end

      if attributes.key?(:'before_name')
        self.before_name = attributes[:'before_name']
      end

      if attributes.key?(:'before_provider')
        self.before_provider = attributes[:'before_provider']
      end

      if attributes.key?(:'before_repo_name')
        self.before_repo_name = attributes[:'before_repo_name']
      end

      if attributes.key?(:'before_repo_owner')
        self.before_repo_owner = attributes[:'before_repo_owner']
      end

      if attributes.key?(:'before_skill_selection_mode')
        self.before_skill_selection_mode = attributes[:'before_skill_selection_mode']
      end

      if attributes.key?(:'before_subpath')
        self.before_subpath = attributes[:'before_subpath']
      end

      if attributes.key?(:'changed')
        self.changed = attributes[:'changed']
      else
        self.changed = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @changed.nil?
        invalid_properties.push('invalid value for "changed", changed cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @changed.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] changed Value to be assigned
    def changed=(changed)
      if changed.nil?
        fail ArgumentError, 'changed cannot be nil'
      end

      @changed = changed
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          after_enabled == o.after_enabled &&
          after_enabled_skill_count == o.after_enabled_skill_count &&
          after_name == o.after_name &&
          after_provider == o.after_provider &&
          after_repo_name == o.after_repo_name &&
          after_repo_owner == o.after_repo_owner &&
          after_skill_selection_mode == o.after_skill_selection_mode &&
          after_subpath == o.after_subpath &&
          before_enabled == o.before_enabled &&
          before_enabled_skill_count == o.before_enabled_skill_count &&
          before_name == o.before_name &&
          before_provider == o.before_provider &&
          before_repo_name == o.before_repo_name &&
          before_repo_owner == o.before_repo_owner &&
          before_skill_selection_mode == o.before_skill_selection_mode &&
          before_subpath == o.before_subpath &&
          changed == o.changed
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [after_enabled, after_enabled_skill_count, after_name, after_provider, after_repo_name, after_repo_owner, after_skill_selection_mode, after_subpath, before_enabled, before_enabled_skill_count, before_name, before_provider, before_repo_name, before_repo_owner, before_skill_selection_mode, before_subpath, changed].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
