=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class AuditLogScheduleOverrideMetadataV2 < ApiModelBase
    # User IDs of users on-call after the override change, comma separated
    attr_accessor :after_user_ids

    # Names of users on-call after the override change, comma separated
    attr_accessor :after_user_names

    # User IDs of users on-call before the override change, comma separated
    attr_accessor :before_user_ids

    # Names of users on-call before the override change, comma separated
    attr_accessor :before_user_names

    # Override end time in the schedule's local timezone
    attr_accessor :end_at

    # Override start time in the schedule's local timezone
    attr_accessor :start_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'after_user_ids' => :'after_user_ids',
        :'after_user_names' => :'after_user_names',
        :'before_user_ids' => :'before_user_ids',
        :'before_user_names' => :'before_user_names',
        :'end_at' => :'end_at',
        :'start_at' => :'start_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'after_user_ids' => :'String',
        :'after_user_names' => :'String',
        :'before_user_ids' => :'String',
        :'before_user_names' => :'String',
        :'end_at' => :'String',
        :'start_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::AuditLogScheduleOverrideMetadataV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::AuditLogScheduleOverrideMetadataV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'after_user_ids')
        self.after_user_ids = attributes[:'after_user_ids']
      else
        self.after_user_ids = nil
      end

      if attributes.key?(:'after_user_names')
        self.after_user_names = attributes[:'after_user_names']
      else
        self.after_user_names = nil
      end

      if attributes.key?(:'before_user_ids')
        self.before_user_ids = attributes[:'before_user_ids']
      else
        self.before_user_ids = nil
      end

      if attributes.key?(:'before_user_names')
        self.before_user_names = attributes[:'before_user_names']
      else
        self.before_user_names = nil
      end

      if attributes.key?(:'end_at')
        self.end_at = attributes[:'end_at']
      else
        self.end_at = nil
      end

      if attributes.key?(:'start_at')
        self.start_at = attributes[:'start_at']
      else
        self.start_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @after_user_ids.nil?
        invalid_properties.push('invalid value for "after_user_ids", after_user_ids cannot be nil.')
      end

      if @after_user_names.nil?
        invalid_properties.push('invalid value for "after_user_names", after_user_names cannot be nil.')
      end

      if @before_user_ids.nil?
        invalid_properties.push('invalid value for "before_user_ids", before_user_ids cannot be nil.')
      end

      if @before_user_names.nil?
        invalid_properties.push('invalid value for "before_user_names", before_user_names cannot be nil.')
      end

      if @end_at.nil?
        invalid_properties.push('invalid value for "end_at", end_at cannot be nil.')
      end

      if @start_at.nil?
        invalid_properties.push('invalid value for "start_at", start_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @after_user_ids.nil?
      return false if @after_user_names.nil?
      return false if @before_user_ids.nil?
      return false if @before_user_names.nil?
      return false if @end_at.nil?
      return false if @start_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] after_user_ids Value to be assigned
    def after_user_ids=(after_user_ids)
      if after_user_ids.nil?
        fail ArgumentError, 'after_user_ids cannot be nil'
      end

      @after_user_ids = after_user_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] after_user_names Value to be assigned
    def after_user_names=(after_user_names)
      if after_user_names.nil?
        fail ArgumentError, 'after_user_names cannot be nil'
      end

      @after_user_names = after_user_names
    end

    # Custom attribute writer method with validation
    # @param [Object] before_user_ids Value to be assigned
    def before_user_ids=(before_user_ids)
      if before_user_ids.nil?
        fail ArgumentError, 'before_user_ids cannot be nil'
      end

      @before_user_ids = before_user_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] before_user_names Value to be assigned
    def before_user_names=(before_user_names)
      if before_user_names.nil?
        fail ArgumentError, 'before_user_names cannot be nil'
      end

      @before_user_names = before_user_names
    end

    # Custom attribute writer method with validation
    # @param [Object] end_at Value to be assigned
    def end_at=(end_at)
      if end_at.nil?
        fail ArgumentError, 'end_at cannot be nil'
      end

      @end_at = end_at
    end

    # Custom attribute writer method with validation
    # @param [Object] start_at Value to be assigned
    def start_at=(start_at)
      if start_at.nil?
        fail ArgumentError, 'start_at cannot be nil'
      end

      @start_at = start_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          after_user_ids == o.after_user_ids &&
          after_user_names == o.after_user_names &&
          before_user_ids == o.before_user_ids &&
          before_user_names == o.before_user_names &&
          end_at == o.end_at &&
          start_at == o.start_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [after_user_ids, after_user_names, before_user_ids, before_user_names, end_at, start_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
