=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class AuditLogExtensionConnectorCalledMetadataV3V2 < ApiModelBase
    # What decided: the connector's access policy, or a decision pinned on this tool (policy, override)
    attr_accessor :access_source

    # What calling the tool does to the connected system, as the tool's own server describes it (read, write, destructive, unknown)
    attr_accessor :_class

    # The incident the call was made for, when incident-scoped
    attr_accessor :incident_id

    # How the call ended (success, error, denied). A denied call was refused by the connector's access policy and never reached the connected system
    attr_accessor :outcome

    # Why the call was allowed or refused (allowed, denied_by_rule, disabled, unknown_rule_type, not_read)
    attr_accessor :reason

    # The kind of connector that was called (mcp, http)
    attr_accessor :source_kind

    # The product surface the call ran from (chat, investigation, explore, mcp_client, verify), or internal for system paths with no surface
    attr_accessor :surface

    # ID of our stored record of this call, absent for a call that was refused
    attr_accessor :telemetry_query_id

    # Whether the call was permitted to change the connected system (true, false)
    attr_accessor :write

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'access_source' => :'access_source',
        :'_class' => :'class',
        :'incident_id' => :'incident_id',
        :'outcome' => :'outcome',
        :'reason' => :'reason',
        :'source_kind' => :'source_kind',
        :'surface' => :'surface',
        :'telemetry_query_id' => :'telemetry_query_id',
        :'write' => :'write'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'access_source' => :'String',
        :'_class' => :'String',
        :'incident_id' => :'String',
        :'outcome' => :'String',
        :'reason' => :'String',
        :'source_kind' => :'String',
        :'surface' => :'String',
        :'telemetry_query_id' => :'String',
        :'write' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::AuditLogExtensionConnectorCalledMetadataV3V2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::AuditLogExtensionConnectorCalledMetadataV3V2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'access_source')
        self.access_source = attributes[:'access_source']
      end

      if attributes.key?(:'_class')
        self._class = attributes[:'_class']
      end

      if attributes.key?(:'incident_id')
        self.incident_id = attributes[:'incident_id']
      end

      if attributes.key?(:'outcome')
        self.outcome = attributes[:'outcome']
      else
        self.outcome = nil
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end

      if attributes.key?(:'source_kind')
        self.source_kind = attributes[:'source_kind']
      else
        self.source_kind = nil
      end

      if attributes.key?(:'surface')
        self.surface = attributes[:'surface']
      else
        self.surface = nil
      end

      if attributes.key?(:'telemetry_query_id')
        self.telemetry_query_id = attributes[:'telemetry_query_id']
      end

      if attributes.key?(:'write')
        self.write = attributes[:'write']
      else
        self.write = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @outcome.nil?
        invalid_properties.push('invalid value for "outcome", outcome cannot be nil.')
      end

      if @source_kind.nil?
        invalid_properties.push('invalid value for "source_kind", source_kind cannot be nil.')
      end

      if @surface.nil?
        invalid_properties.push('invalid value for "surface", surface cannot be nil.')
      end

      if @write.nil?
        invalid_properties.push('invalid value for "write", write cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @outcome.nil?
      return false if @source_kind.nil?
      return false if @surface.nil?
      return false if @write.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] outcome Value to be assigned
    def outcome=(outcome)
      if outcome.nil?
        fail ArgumentError, 'outcome cannot be nil'
      end

      @outcome = outcome
    end

    # Custom attribute writer method with validation
    # @param [Object] source_kind Value to be assigned
    def source_kind=(source_kind)
      if source_kind.nil?
        fail ArgumentError, 'source_kind cannot be nil'
      end

      @source_kind = source_kind
    end

    # Custom attribute writer method with validation
    # @param [Object] surface Value to be assigned
    def surface=(surface)
      if surface.nil?
        fail ArgumentError, 'surface cannot be nil'
      end

      @surface = surface
    end

    # Custom attribute writer method with validation
    # @param [Object] write Value to be assigned
    def write=(write)
      if write.nil?
        fail ArgumentError, 'write cannot be nil'
      end

      @write = write
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          access_source == o.access_source &&
          _class == o._class &&
          incident_id == o.incident_id &&
          outcome == o.outcome &&
          reason == o.reason &&
          source_kind == o.source_kind &&
          surface == o.surface &&
          telemetry_query_id == o.telemetry_query_id &&
          write == o.write
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [access_source, _class, incident_id, outcome, reason, source_kind, surface, telemetry_query_id, write].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
