=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class AuditLogTelemetryDataSourceToolOverridesChangedMetadataV2 < ApiModelBase
    # The tool's pins after the change, as JSON; empty when the change removed the last one
    attr_accessor :after

    # The tool's pins before the change, as JSON; empty when nothing was pinned on it
    attr_accessor :before

    # Shared by every entry the same save produced, so the decision that changed and the access it reached can be read together
    attr_accessor :change_id

    # The name of the tool whose pinned decisions changed
    attr_accessor :tool

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'after' => :'after',
        :'before' => :'before',
        :'change_id' => :'change_id',
        :'tool' => :'tool'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'after' => :'String',
        :'before' => :'String',
        :'change_id' => :'String',
        :'tool' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::AuditLogTelemetryDataSourceToolOverridesChangedMetadataV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::AuditLogTelemetryDataSourceToolOverridesChangedMetadataV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'after')
        self.after = attributes[:'after']
      else
        self.after = nil
      end

      if attributes.key?(:'before')
        self.before = attributes[:'before']
      else
        self.before = nil
      end

      if attributes.key?(:'change_id')
        self.change_id = attributes[:'change_id']
      else
        self.change_id = nil
      end

      if attributes.key?(:'tool')
        self.tool = attributes[:'tool']
      else
        self.tool = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @after.nil?
        invalid_properties.push('invalid value for "after", after cannot be nil.')
      end

      if @before.nil?
        invalid_properties.push('invalid value for "before", before cannot be nil.')
      end

      if @change_id.nil?
        invalid_properties.push('invalid value for "change_id", change_id cannot be nil.')
      end

      if @tool.nil?
        invalid_properties.push('invalid value for "tool", tool cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @after.nil?
      return false if @before.nil?
      return false if @change_id.nil?
      return false if @tool.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] after Value to be assigned
    def after=(after)
      if after.nil?
        fail ArgumentError, 'after cannot be nil'
      end

      @after = after
    end

    # Custom attribute writer method with validation
    # @param [Object] before Value to be assigned
    def before=(before)
      if before.nil?
        fail ArgumentError, 'before cannot be nil'
      end

      @before = before
    end

    # Custom attribute writer method with validation
    # @param [Object] change_id Value to be assigned
    def change_id=(change_id)
      if change_id.nil?
        fail ArgumentError, 'change_id cannot be nil'
      end

      @change_id = change_id
    end

    # Custom attribute writer method with validation
    # @param [Object] tool Value to be assigned
    def tool=(tool)
      if tool.nil?
        fail ArgumentError, 'tool cannot be nil'
      end

      @tool = tool
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          after == o.after &&
          before == o.before &&
          change_id == o.change_id &&
          tool == o.tool
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [after, before, change_id, tool].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
