=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class CatalogBulkUpdateEntriesPayloadV3 < ApiModelBase
    # The unique identifier of the catalog type containing the entries
    attr_accessor :catalog_type_id

    # A list of entries to update with their new values. Maximum 250 entries per request.
    attr_accessor :entries

    # Optional list of specific attribute IDs to update across all entries. When provided, only these attributes in attribute_values will be updated and all other attributes will be preserved. This parameter only affects attribute_values - it does not affect core entry fields like name, rank, aliases, or external_id, which follow their individual omission rules.
    attr_accessor :update_attributes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'catalog_type_id' => :'catalog_type_id',
        :'entries' => :'entries',
        :'update_attributes' => :'update_attributes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'catalog_type_id' => :'String',
        :'entries' => :'Array<PartialEntryPayloadV3>',
        :'update_attributes' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::CatalogBulkUpdateEntriesPayloadV3` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::CatalogBulkUpdateEntriesPayloadV3`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'catalog_type_id')
        self.catalog_type_id = attributes[:'catalog_type_id']
      else
        self.catalog_type_id = nil
      end

      if attributes.key?(:'entries')
        if (value = attributes[:'entries']).is_a?(Array)
          self.entries = value
        end
      else
        self.entries = nil
      end

      if attributes.key?(:'update_attributes')
        if (value = attributes[:'update_attributes']).is_a?(Array)
          self.update_attributes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @catalog_type_id.nil?
        invalid_properties.push('invalid value for "catalog_type_id", catalog_type_id cannot be nil.')
      end

      if @entries.nil?
        invalid_properties.push('invalid value for "entries", entries cannot be nil.')
      end

      if @entries.length > 250
        invalid_properties.push('invalid value for "entries", number of items must be less than or equal to 250.')
      end

      if @entries.length < 1
        invalid_properties.push('invalid value for "entries", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @catalog_type_id.nil?
      return false if @entries.nil?
      return false if @entries.length > 250
      return false if @entries.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] catalog_type_id Value to be assigned
    def catalog_type_id=(catalog_type_id)
      if catalog_type_id.nil?
        fail ArgumentError, 'catalog_type_id cannot be nil'
      end

      @catalog_type_id = catalog_type_id
    end

    # Custom attribute writer method with validation
    # @param [Object] entries Value to be assigned
    def entries=(entries)
      if entries.nil?
        fail ArgumentError, 'entries cannot be nil'
      end

      if entries.length > 250
        fail ArgumentError, 'invalid value for "entries", number of items must be less than or equal to 250.'
      end

      if entries.length < 1
        fail ArgumentError, 'invalid value for "entries", number of items must be greater than or equal to 1.'
      end

      @entries = entries
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          catalog_type_id == o.catalog_type_id &&
          entries == o.entries &&
          update_attributes == o.update_attributes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [catalog_type_id, entries, update_attributes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
