=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class CatalogEntryV3 < ApiModelBase
    # Optional aliases that can be used to reference this entry
    attr_accessor :aliases

    # When this entry was archived
    attr_accessor :archived_at

    # Values of this entry
    attr_accessor :attribute_values

    # ID of this catalog type
    attr_accessor :catalog_type_id

    # When this entry was created
    attr_accessor :created_at

    # An optional alternative ID for this entry, which is ensured to be unique for the type
    attr_accessor :external_id

    # ID of this catalog entry
    attr_accessor :id

    # Name is the human readable name of this entry
    attr_accessor :name

    # When catalog type is ranked, this is used to help order things
    attr_accessor :rank

    # When this entry was last updated
    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'aliases' => :'aliases',
        :'archived_at' => :'archived_at',
        :'attribute_values' => :'attribute_values',
        :'catalog_type_id' => :'catalog_type_id',
        :'created_at' => :'created_at',
        :'external_id' => :'external_id',
        :'id' => :'id',
        :'name' => :'name',
        :'rank' => :'rank',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'aliases' => :'Array<String>',
        :'archived_at' => :'Time',
        :'attribute_values' => :'Hash<String, CatalogEntryEngineParamBindingV3>',
        :'catalog_type_id' => :'String',
        :'created_at' => :'Time',
        :'external_id' => :'String',
        :'id' => :'String',
        :'name' => :'String',
        :'rank' => :'Integer',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::CatalogEntryV3` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::CatalogEntryV3`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'aliases')
        if (value = attributes[:'aliases']).is_a?(Array)
          self.aliases = value
        end
      else
        self.aliases = nil
      end

      if attributes.key?(:'archived_at')
        self.archived_at = attributes[:'archived_at']
      end

      if attributes.key?(:'attribute_values')
        if (value = attributes[:'attribute_values']).is_a?(Hash)
          self.attribute_values = value
        end
      else
        self.attribute_values = nil
      end

      if attributes.key?(:'catalog_type_id')
        self.catalog_type_id = attributes[:'catalog_type_id']
      else
        self.catalog_type_id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'rank')
        self.rank = attributes[:'rank']
      else
        self.rank = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @aliases.nil?
        invalid_properties.push('invalid value for "aliases", aliases cannot be nil.')
      end

      if @attribute_values.nil?
        invalid_properties.push('invalid value for "attribute_values", attribute_values cannot be nil.')
      end

      if @catalog_type_id.nil?
        invalid_properties.push('invalid value for "catalog_type_id", catalog_type_id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @rank.nil?
        invalid_properties.push('invalid value for "rank", rank cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @aliases.nil?
      return false if @attribute_values.nil?
      return false if @catalog_type_id.nil?
      return false if @created_at.nil?
      return false if @id.nil?
      return false if @name.nil?
      return false if @rank.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] aliases Value to be assigned
    def aliases=(aliases)
      if aliases.nil?
        fail ArgumentError, 'aliases cannot be nil'
      end

      @aliases = aliases
    end

    # Custom attribute writer method with validation
    # @param [Object] attribute_values Value to be assigned
    def attribute_values=(attribute_values)
      if attribute_values.nil?
        fail ArgumentError, 'attribute_values cannot be nil'
      end

      @attribute_values = attribute_values
    end

    # Custom attribute writer method with validation
    # @param [Object] catalog_type_id Value to be assigned
    def catalog_type_id=(catalog_type_id)
      if catalog_type_id.nil?
        fail ArgumentError, 'catalog_type_id cannot be nil'
      end

      @catalog_type_id = catalog_type_id
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] rank Value to be assigned
    def rank=(rank)
      if rank.nil?
        fail ArgumentError, 'rank cannot be nil'
      end

      @rank = rank
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          aliases == o.aliases &&
          archived_at == o.archived_at &&
          attribute_values == o.attribute_values &&
          catalog_type_id == o.catalog_type_id &&
          created_at == o.created_at &&
          external_id == o.external_id &&
          id == o.id &&
          name == o.name &&
          rank == o.rank &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [aliases, archived_at, attribute_values, catalog_type_id, created_at, external_id, id, name, rank, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
