=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class ChatChannelSlimV2 < ApiModelBase
    # ID of the Microsoft Teams channel, if there is one
    attr_accessor :microsoft_teams_channel_id

    # ID of the Microsoft Teams team, if there is one
    attr_accessor :microsoft_teams_team_id

    # ID of the Slack channel, if there is one
    attr_accessor :slack_channel_id

    # ID of the Slack team, if there is one
    attr_accessor :slack_team_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'microsoft_teams_channel_id' => :'microsoft_teams_channel_id',
        :'microsoft_teams_team_id' => :'microsoft_teams_team_id',
        :'slack_channel_id' => :'slack_channel_id',
        :'slack_team_id' => :'slack_team_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'microsoft_teams_channel_id' => :'String',
        :'microsoft_teams_team_id' => :'String',
        :'slack_channel_id' => :'String',
        :'slack_team_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::ChatChannelSlimV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::ChatChannelSlimV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'microsoft_teams_channel_id')
        self.microsoft_teams_channel_id = attributes[:'microsoft_teams_channel_id']
      end

      if attributes.key?(:'microsoft_teams_team_id')
        self.microsoft_teams_team_id = attributes[:'microsoft_teams_team_id']
      end

      if attributes.key?(:'slack_channel_id')
        self.slack_channel_id = attributes[:'slack_channel_id']
      end

      if attributes.key?(:'slack_team_id')
        self.slack_team_id = attributes[:'slack_team_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          microsoft_teams_channel_id == o.microsoft_teams_channel_id &&
          microsoft_teams_team_id == o.microsoft_teams_team_id &&
          slack_channel_id == o.slack_channel_id &&
          slack_team_id == o.slack_team_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [microsoft_teams_channel_id, microsoft_teams_team_id, slack_channel_id, slack_team_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
