=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class CustomFieldFilterByOptionsV2 < ApiModelBase
    # This must be an attribute of the catalog type of this custom field. It must be an attribute that points to another catalog type (so not a plain string, number, or boolean attribute).
    attr_accessor :catalog_attribute_id

    # This must be the ID of a custom field, which must have values of the same type as the attribute you are filtering by.  When this filtering field is set on an incident, the options for this custom field will be filtered to only those with the attribute value that matches the value of the filtering field.
    attr_accessor :custom_field_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'catalog_attribute_id' => :'catalog_attribute_id',
        :'custom_field_id' => :'custom_field_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'catalog_attribute_id' => :'String',
        :'custom_field_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::CustomFieldFilterByOptionsV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::CustomFieldFilterByOptionsV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'catalog_attribute_id')
        self.catalog_attribute_id = attributes[:'catalog_attribute_id']
      else
        self.catalog_attribute_id = nil
      end

      if attributes.key?(:'custom_field_id')
        self.custom_field_id = attributes[:'custom_field_id']
      else
        self.custom_field_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @catalog_attribute_id.nil?
        invalid_properties.push('invalid value for "catalog_attribute_id", catalog_attribute_id cannot be nil.')
      end

      if @custom_field_id.nil?
        invalid_properties.push('invalid value for "custom_field_id", custom_field_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @catalog_attribute_id.nil?
      return false if @custom_field_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] catalog_attribute_id Value to be assigned
    def catalog_attribute_id=(catalog_attribute_id)
      if catalog_attribute_id.nil?
        fail ArgumentError, 'catalog_attribute_id cannot be nil'
      end

      @catalog_attribute_id = catalog_attribute_id
    end

    # Custom attribute writer method with validation
    # @param [Object] custom_field_id Value to be assigned
    def custom_field_id=(custom_field_id)
      if custom_field_id.nil?
        fail ArgumentError, 'custom_field_id cannot be nil'
      end

      @custom_field_id = custom_field_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          catalog_attribute_id == o.catalog_attribute_id &&
          custom_field_id == o.custom_field_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [catalog_attribute_id, custom_field_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
