=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class EscalationPathNodeLevelV2 < ApiModelBase
    # Controls the behaviour of acknowledgements for this level, with 'first' cancelling all other escalations on the same level when someone acks  Known values: `all`, `first`
    attr_accessor :ack_mode

    attr_accessor :retry_config

    attr_accessor :round_robin_config

    # The targets (users or schedules) for this level
    attr_accessor :targets

    # If the time to ack is relative to a time window, this defines whether we move when the window is active or inactive  Known values: `active`, `inactive`
    attr_accessor :time_to_ack_interval_condition

    # How long should we wait for this level to acknowledge before proceeding to the next node in the path?
    attr_accessor :time_to_ack_seconds

    # If the time to ack is relative to a time window, this identifies which window it is relative to
    attr_accessor :time_to_ack_weekday_interval_config_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ack_mode' => :'ack_mode',
        :'retry_config' => :'retry_config',
        :'round_robin_config' => :'round_robin_config',
        :'targets' => :'targets',
        :'time_to_ack_interval_condition' => :'time_to_ack_interval_condition',
        :'time_to_ack_seconds' => :'time_to_ack_seconds',
        :'time_to_ack_weekday_interval_config_id' => :'time_to_ack_weekday_interval_config_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ack_mode' => :'String',
        :'retry_config' => :'EscalationPathRetryConfigV2',
        :'round_robin_config' => :'EscalationPathRoundRobinConfigV2',
        :'targets' => :'Array<EscalationPathTargetV2>',
        :'time_to_ack_interval_condition' => :'String',
        :'time_to_ack_seconds' => :'Integer',
        :'time_to_ack_weekday_interval_config_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::EscalationPathNodeLevelV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::EscalationPathNodeLevelV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ack_mode')
        self.ack_mode = attributes[:'ack_mode']
      end

      if attributes.key?(:'retry_config')
        self.retry_config = attributes[:'retry_config']
      end

      if attributes.key?(:'round_robin_config')
        self.round_robin_config = attributes[:'round_robin_config']
      end

      if attributes.key?(:'targets')
        if (value = attributes[:'targets']).is_a?(Array)
          self.targets = value
        end
      else
        self.targets = nil
      end

      if attributes.key?(:'time_to_ack_interval_condition')
        self.time_to_ack_interval_condition = attributes[:'time_to_ack_interval_condition']
      end

      if attributes.key?(:'time_to_ack_seconds')
        self.time_to_ack_seconds = attributes[:'time_to_ack_seconds']
      end

      if attributes.key?(:'time_to_ack_weekday_interval_config_id')
        self.time_to_ack_weekday_interval_config_id = attributes[:'time_to_ack_weekday_interval_config_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @targets.nil?
        invalid_properties.push('invalid value for "targets", targets cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @targets.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] targets Value to be assigned
    def targets=(targets)
      if targets.nil?
        fail ArgumentError, 'targets cannot be nil'
      end

      @targets = targets
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ack_mode == o.ack_mode &&
          retry_config == o.retry_config &&
          round_robin_config == o.round_robin_config &&
          targets == o.targets &&
          time_to_ack_interval_condition == o.time_to_ack_interval_condition &&
          time_to_ack_seconds == o.time_to_ack_seconds &&
          time_to_ack_weekday_interval_config_id == o.time_to_ack_weekday_interval_config_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ack_mode, retry_config, round_robin_config, targets, time_to_ack_interval_condition, time_to_ack_seconds, time_to_ack_weekday_interval_config_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
