=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  # Narrows one of a report's schedules to some of its rotations.
  class PayReportRotationFilterV2 < ApiModelBase
    # Which of the schedule's rotations to include. To include all of them, leave this schedule out of rotation_filters rather than listing every rotation here.
    attr_accessor :rotation_ids

    # The schedule to narrow. Must also appear in schedule_ids.
    attr_accessor :schedule_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rotation_ids' => :'rotation_ids',
        :'schedule_id' => :'schedule_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rotation_ids' => :'Array<String>',
        :'schedule_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::PayReportRotationFilterV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::PayReportRotationFilterV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rotation_ids')
        if (value = attributes[:'rotation_ids']).is_a?(Array)
          self.rotation_ids = value
        end
      else
        self.rotation_ids = nil
      end

      if attributes.key?(:'schedule_id')
        self.schedule_id = attributes[:'schedule_id']
      else
        self.schedule_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @rotation_ids.nil?
        invalid_properties.push('invalid value for "rotation_ids", rotation_ids cannot be nil.')
      end

      if @rotation_ids.length < 1
        invalid_properties.push('invalid value for "rotation_ids", number of items must be greater than or equal to 1.')
      end

      if @schedule_id.nil?
        invalid_properties.push('invalid value for "schedule_id", schedule_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @rotation_ids.nil?
      return false if @rotation_ids.length < 1
      return false if @schedule_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] rotation_ids Value to be assigned
    def rotation_ids=(rotation_ids)
      if rotation_ids.nil?
        fail ArgumentError, 'rotation_ids cannot be nil'
      end

      if rotation_ids.length < 1
        fail ArgumentError, 'invalid value for "rotation_ids", number of items must be greater than or equal to 1.'
      end

      @rotation_ids = rotation_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] schedule_id Value to be assigned
    def schedule_id=(schedule_id)
      if schedule_id.nil?
        fail ArgumentError, 'schedule_id cannot be nil'
      end

      @schedule_id = schedule_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rotation_ids == o.rotation_ids &&
          schedule_id == o.schedule_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rotation_ids, schedule_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
