=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  # Set when policy_type is schedule. Describes a gap in on-call cover.
  class PolicyFindingScheduleV2 < ApiModelBase
    # Why the gap exists  Known values: `nobody_scheduled`, `no_on_call_seat`, `user_deactivated`, `notifications_paused`
    attr_accessor :cause

    # When the gap ends
    attr_accessor :end_at

    # Whether part of the gap has nobody scheduled at all, so impacted_users doesn't fully explain it
    attr_accessor :has_unscheduled_time

    # Users scheduled across the gap whose entries don't count as cover
    attr_accessor :impacted_users

    # The rotation with the gap, when the policy evaluates per rotation
    attr_accessor :rotation_id

    # The schedule with the gap
    attr_accessor :schedule_id

    # When the gap starts
    attr_accessor :start_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cause' => :'cause',
        :'end_at' => :'end_at',
        :'has_unscheduled_time' => :'has_unscheduled_time',
        :'impacted_users' => :'impacted_users',
        :'rotation_id' => :'rotation_id',
        :'schedule_id' => :'schedule_id',
        :'start_at' => :'start_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cause' => :'String',
        :'end_at' => :'Time',
        :'has_unscheduled_time' => :'Boolean',
        :'impacted_users' => :'Array<PolicyFindingScheduleImpactedUserV2>',
        :'rotation_id' => :'String',
        :'schedule_id' => :'String',
        :'start_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::PolicyFindingScheduleV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::PolicyFindingScheduleV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cause')
        self.cause = attributes[:'cause']
      end

      if attributes.key?(:'end_at')
        self.end_at = attributes[:'end_at']
      else
        self.end_at = nil
      end

      if attributes.key?(:'has_unscheduled_time')
        self.has_unscheduled_time = attributes[:'has_unscheduled_time']
      end

      if attributes.key?(:'impacted_users')
        if (value = attributes[:'impacted_users']).is_a?(Array)
          self.impacted_users = value
        end
      end

      if attributes.key?(:'rotation_id')
        self.rotation_id = attributes[:'rotation_id']
      end

      if attributes.key?(:'schedule_id')
        self.schedule_id = attributes[:'schedule_id']
      else
        self.schedule_id = nil
      end

      if attributes.key?(:'start_at')
        self.start_at = attributes[:'start_at']
      else
        self.start_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @end_at.nil?
        invalid_properties.push('invalid value for "end_at", end_at cannot be nil.')
      end

      if @schedule_id.nil?
        invalid_properties.push('invalid value for "schedule_id", schedule_id cannot be nil.')
      end

      if @start_at.nil?
        invalid_properties.push('invalid value for "start_at", start_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @end_at.nil?
      return false if @schedule_id.nil?
      return false if @start_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] end_at Value to be assigned
    def end_at=(end_at)
      if end_at.nil?
        fail ArgumentError, 'end_at cannot be nil'
      end

      @end_at = end_at
    end

    # Custom attribute writer method with validation
    # @param [Object] schedule_id Value to be assigned
    def schedule_id=(schedule_id)
      if schedule_id.nil?
        fail ArgumentError, 'schedule_id cannot be nil'
      end

      @schedule_id = schedule_id
    end

    # Custom attribute writer method with validation
    # @param [Object] start_at Value to be assigned
    def start_at=(start_at)
      if start_at.nil?
        fail ArgumentError, 'start_at cannot be nil'
      end

      @start_at = start_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cause == o.cause &&
          end_at == o.end_at &&
          has_unscheduled_time == o.has_unscheduled_time &&
          impacted_users == o.impacted_users &&
          rotation_id == o.rotation_id &&
          schedule_id == o.schedule_id &&
          start_at == o.start_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cause, end_at, has_unscheduled_time, impacted_users, rotation_id, schedule_id, start_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
