=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class PostmortemDocumentV1 < ApiModelBase
    # Timestamp for when the document was created
    attr_accessor :created_at

    # A URL to view the post-mortem document in the incident.io dashboard
    attr_accessor :document_url

    # The list of users who have edited this post-mortem document
    attr_accessor :editors

    # URLs of any external locations this document has been exported to
    attr_accessor :exported_urls

    # Unique identifier for the post-mortem document
    attr_accessor :id

    # The unique identifier of the incident that this post-mortem document belongs to
    attr_accessor :incident_id

    # The current status of this post-mortem document  Known values: `in_progress`, `in_review`, `completed`
    attr_accessor :status

    # The display title of the post-mortem document
    attr_accessor :title

    # Whether this is a native incident.io post-mortem or one hosted in an external provider  Known values: `in_app`, `external`
    attr_accessor :type

    # Timestamp for when the document was last updated
    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_at' => :'created_at',
        :'document_url' => :'document_url',
        :'editors' => :'editors',
        :'exported_urls' => :'exported_urls',
        :'id' => :'id',
        :'incident_id' => :'incident_id',
        :'status' => :'status',
        :'title' => :'title',
        :'type' => :'type',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created_at' => :'Time',
        :'document_url' => :'String',
        :'editors' => :'Array<UserV1>',
        :'exported_urls' => :'Array<String>',
        :'id' => :'String',
        :'incident_id' => :'String',
        :'status' => :'String',
        :'title' => :'String',
        :'type' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::PostmortemDocumentV1` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::PostmortemDocumentV1`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'document_url')
        self.document_url = attributes[:'document_url']
      else
        self.document_url = nil
      end

      if attributes.key?(:'editors')
        if (value = attributes[:'editors']).is_a?(Array)
          self.editors = value
        end
      else
        self.editors = nil
      end

      if attributes.key?(:'exported_urls')
        if (value = attributes[:'exported_urls']).is_a?(Array)
          self.exported_urls = value
        end
      else
        self.exported_urls = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'incident_id')
        self.incident_id = attributes[:'incident_id']
      else
        self.incident_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @document_url.nil?
        invalid_properties.push('invalid value for "document_url", document_url cannot be nil.')
      end

      if @editors.nil?
        invalid_properties.push('invalid value for "editors", editors cannot be nil.')
      end

      if @exported_urls.nil?
        invalid_properties.push('invalid value for "exported_urls", exported_urls cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @incident_id.nil?
        invalid_properties.push('invalid value for "incident_id", incident_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @created_at.nil?
      return false if @document_url.nil?
      return false if @editors.nil?
      return false if @exported_urls.nil?
      return false if @id.nil?
      return false if @incident_id.nil?
      return false if @status.nil?
      return false if @title.nil?
      return false if @type.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] document_url Value to be assigned
    def document_url=(document_url)
      if document_url.nil?
        fail ArgumentError, 'document_url cannot be nil'
      end

      @document_url = document_url
    end

    # Custom attribute writer method with validation
    # @param [Object] editors Value to be assigned
    def editors=(editors)
      if editors.nil?
        fail ArgumentError, 'editors cannot be nil'
      end

      @editors = editors
    end

    # Custom attribute writer method with validation
    # @param [Object] exported_urls Value to be assigned
    def exported_urls=(exported_urls)
      if exported_urls.nil?
        fail ArgumentError, 'exported_urls cannot be nil'
      end

      @exported_urls = exported_urls
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] incident_id Value to be assigned
    def incident_id=(incident_id)
      if incident_id.nil?
        fail ArgumentError, 'incident_id cannot be nil'
      end

      @incident_id = incident_id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          document_url == o.document_url &&
          editors == o.editors &&
          exported_urls == o.exported_urls &&
          id == o.id &&
          incident_id == o.incident_id &&
          status == o.status &&
          title == o.title &&
          type == o.type &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created_at, document_url, editors, exported_urls, id, incident_id, status, title, type, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
