=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  # Availability of a status page component over a requested time window.
  class StatusPageComponentAvailabilityV2 < ApiModelBase
    # Availability over the window as a percentage, floored (for example \"99.94\"). Omitted when we have no data covering the window.
    attr_accessor :availability_percent

    # ID of the component. This may be found by calling the ShowStatusPageStructure endpoint.
    attr_accessor :component_id

    # Earliest time we have status data for this component. Before this, availability is unknown rather than assumed operational.
    attr_accessor :data_available_since

    # End of the requested availability window
    attr_accessor :end_at

    # Start of the requested availability window
    attr_accessor :start_at

    # ID of the status page
    attr_accessor :status_page_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'availability_percent' => :'availability_percent',
        :'component_id' => :'component_id',
        :'data_available_since' => :'data_available_since',
        :'end_at' => :'end_at',
        :'start_at' => :'start_at',
        :'status_page_id' => :'status_page_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'availability_percent' => :'String',
        :'component_id' => :'String',
        :'data_available_since' => :'Time',
        :'end_at' => :'Time',
        :'start_at' => :'Time',
        :'status_page_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::StatusPageComponentAvailabilityV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::StatusPageComponentAvailabilityV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'availability_percent')
        self.availability_percent = attributes[:'availability_percent']
      end

      if attributes.key?(:'component_id')
        self.component_id = attributes[:'component_id']
      else
        self.component_id = nil
      end

      if attributes.key?(:'data_available_since')
        self.data_available_since = attributes[:'data_available_since']
      else
        self.data_available_since = nil
      end

      if attributes.key?(:'end_at')
        self.end_at = attributes[:'end_at']
      else
        self.end_at = nil
      end

      if attributes.key?(:'start_at')
        self.start_at = attributes[:'start_at']
      else
        self.start_at = nil
      end

      if attributes.key?(:'status_page_id')
        self.status_page_id = attributes[:'status_page_id']
      else
        self.status_page_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @component_id.nil?
        invalid_properties.push('invalid value for "component_id", component_id cannot be nil.')
      end

      if @data_available_since.nil?
        invalid_properties.push('invalid value for "data_available_since", data_available_since cannot be nil.')
      end

      if @end_at.nil?
        invalid_properties.push('invalid value for "end_at", end_at cannot be nil.')
      end

      if @start_at.nil?
        invalid_properties.push('invalid value for "start_at", start_at cannot be nil.')
      end

      if @status_page_id.nil?
        invalid_properties.push('invalid value for "status_page_id", status_page_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @component_id.nil?
      return false if @data_available_since.nil?
      return false if @end_at.nil?
      return false if @start_at.nil?
      return false if @status_page_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] component_id Value to be assigned
    def component_id=(component_id)
      if component_id.nil?
        fail ArgumentError, 'component_id cannot be nil'
      end

      @component_id = component_id
    end

    # Custom attribute writer method with validation
    # @param [Object] data_available_since Value to be assigned
    def data_available_since=(data_available_since)
      if data_available_since.nil?
        fail ArgumentError, 'data_available_since cannot be nil'
      end

      @data_available_since = data_available_since
    end

    # Custom attribute writer method with validation
    # @param [Object] end_at Value to be assigned
    def end_at=(end_at)
      if end_at.nil?
        fail ArgumentError, 'end_at cannot be nil'
      end

      @end_at = end_at
    end

    # Custom attribute writer method with validation
    # @param [Object] start_at Value to be assigned
    def start_at=(start_at)
      if start_at.nil?
        fail ArgumentError, 'start_at cannot be nil'
      end

      @start_at = start_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status_page_id Value to be assigned
    def status_page_id=(status_page_id)
      if status_page_id.nil?
        fail ArgumentError, 'status_page_id cannot be nil'
      end

      @status_page_id = status_page_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          availability_percent == o.availability_percent &&
          component_id == o.component_id &&
          data_available_since == o.data_available_since &&
          end_at == o.end_at &&
          start_at == o.start_at &&
          status_page_id == o.status_page_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [availability_percent, component_id, data_available_since, end_at, start_at, status_page_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
