=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class StatusPageMaintenanceV2 < ApiModelBase
    # Whether updates are published automatically, moving this maintenance window to in progress at its start time and to complete at its end time
    attr_accessor :automate_maintenance_status

    # A list of time periods where components were under maintenance during this status page maintenance window
    attr_accessor :component_maintenance_periods

    # A unique ID for this status page maintenance window
    attr_accessor :id

    # Current status for this maintenance window  Known values: `maintenance_scheduled`, `maintenance_in_progress`, `maintenance_complete`
    attr_accessor :maintenance_status

    # A title for the maintenance window
    attr_accessor :name

    # When this status page maintenance window was published to the status page
    attr_accessor :published_at

    # The ID of the corresponding status page
    attr_accessor :status_page_id

    # A list of updates posted to this status page maintenance window
    attr_accessor :updates

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'automate_maintenance_status' => :'automate_maintenance_status',
        :'component_maintenance_periods' => :'component_maintenance_periods',
        :'id' => :'id',
        :'maintenance_status' => :'maintenance_status',
        :'name' => :'name',
        :'published_at' => :'published_at',
        :'status_page_id' => :'status_page_id',
        :'updates' => :'updates'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'automate_maintenance_status' => :'Boolean',
        :'component_maintenance_periods' => :'Array<StatusPageMaintenanceComponentMaintenancePeriodV2>',
        :'id' => :'String',
        :'maintenance_status' => :'String',
        :'name' => :'String',
        :'published_at' => :'Time',
        :'status_page_id' => :'String',
        :'updates' => :'Array<StatusPageMaintenanceUpdateV2>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::StatusPageMaintenanceV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::StatusPageMaintenanceV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'automate_maintenance_status')
        self.automate_maintenance_status = attributes[:'automate_maintenance_status']
      else
        self.automate_maintenance_status = nil
      end

      if attributes.key?(:'component_maintenance_periods')
        if (value = attributes[:'component_maintenance_periods']).is_a?(Array)
          self.component_maintenance_periods = value
        end
      else
        self.component_maintenance_periods = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'maintenance_status')
        self.maintenance_status = attributes[:'maintenance_status']
      else
        self.maintenance_status = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'published_at')
        self.published_at = attributes[:'published_at']
      else
        self.published_at = nil
      end

      if attributes.key?(:'status_page_id')
        self.status_page_id = attributes[:'status_page_id']
      else
        self.status_page_id = nil
      end

      if attributes.key?(:'updates')
        if (value = attributes[:'updates']).is_a?(Array)
          self.updates = value
        end
      else
        self.updates = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @automate_maintenance_status.nil?
        invalid_properties.push('invalid value for "automate_maintenance_status", automate_maintenance_status cannot be nil.')
      end

      if @component_maintenance_periods.nil?
        invalid_properties.push('invalid value for "component_maintenance_periods", component_maintenance_periods cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @maintenance_status.nil?
        invalid_properties.push('invalid value for "maintenance_status", maintenance_status cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @published_at.nil?
        invalid_properties.push('invalid value for "published_at", published_at cannot be nil.')
      end

      if @status_page_id.nil?
        invalid_properties.push('invalid value for "status_page_id", status_page_id cannot be nil.')
      end

      if @updates.nil?
        invalid_properties.push('invalid value for "updates", updates cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @automate_maintenance_status.nil?
      return false if @component_maintenance_periods.nil?
      return false if @id.nil?
      return false if @maintenance_status.nil?
      return false if @name.nil?
      return false if @published_at.nil?
      return false if @status_page_id.nil?
      return false if @updates.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] automate_maintenance_status Value to be assigned
    def automate_maintenance_status=(automate_maintenance_status)
      if automate_maintenance_status.nil?
        fail ArgumentError, 'automate_maintenance_status cannot be nil'
      end

      @automate_maintenance_status = automate_maintenance_status
    end

    # Custom attribute writer method with validation
    # @param [Object] component_maintenance_periods Value to be assigned
    def component_maintenance_periods=(component_maintenance_periods)
      if component_maintenance_periods.nil?
        fail ArgumentError, 'component_maintenance_periods cannot be nil'
      end

      @component_maintenance_periods = component_maintenance_periods
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] maintenance_status Value to be assigned
    def maintenance_status=(maintenance_status)
      if maintenance_status.nil?
        fail ArgumentError, 'maintenance_status cannot be nil'
      end

      @maintenance_status = maintenance_status
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] published_at Value to be assigned
    def published_at=(published_at)
      if published_at.nil?
        fail ArgumentError, 'published_at cannot be nil'
      end

      @published_at = published_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status_page_id Value to be assigned
    def status_page_id=(status_page_id)
      if status_page_id.nil?
        fail ArgumentError, 'status_page_id cannot be nil'
      end

      @status_page_id = status_page_id
    end

    # Custom attribute writer method with validation
    # @param [Object] updates Value to be assigned
    def updates=(updates)
      if updates.nil?
        fail ArgumentError, 'updates cannot be nil'
      end

      @updates = updates
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          automate_maintenance_status == o.automate_maintenance_status &&
          component_maintenance_periods == o.component_maintenance_periods &&
          id == o.id &&
          maintenance_status == o.maintenance_status &&
          name == o.name &&
          published_at == o.published_at &&
          status_page_id == o.status_page_id &&
          updates == o.updates
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [automate_maintenance_status, component_maintenance_periods, id, maintenance_status, name, published_at, status_page_id, updates].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
