=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class StatusPageIncidentV2 < ApiModelBase
    # A list of time periods that this status page incident had an impact on a component
    attr_accessor :component_impacts

    # A unique ID for this status page incident
    attr_accessor :id

    # Current status for this incident  Known values: `investigating`, `identified`, `monitoring`, `resolved`
    attr_accessor :incident_status

    # A title for the incident
    attr_accessor :name

    # When this status page incident was published to the status page
    attr_accessor :published_at

    # The ID of the corresponding status page
    attr_accessor :status_page_id

    # A list of updates posted to this status page incident
    attr_accessor :updates

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'component_impacts' => :'component_impacts',
        :'id' => :'id',
        :'incident_status' => :'incident_status',
        :'name' => :'name',
        :'published_at' => :'published_at',
        :'status_page_id' => :'status_page_id',
        :'updates' => :'updates'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'component_impacts' => :'Array<StatusPageIncidentComponentImpactV2>',
        :'id' => :'String',
        :'incident_status' => :'String',
        :'name' => :'String',
        :'published_at' => :'Time',
        :'status_page_id' => :'String',
        :'updates' => :'Array<StatusPageIncidentUpdateV2>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::StatusPageIncidentV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::StatusPageIncidentV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'component_impacts')
        if (value = attributes[:'component_impacts']).is_a?(Array)
          self.component_impacts = value
        end
      else
        self.component_impacts = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'incident_status')
        self.incident_status = attributes[:'incident_status']
      else
        self.incident_status = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'published_at')
        self.published_at = attributes[:'published_at']
      else
        self.published_at = nil
      end

      if attributes.key?(:'status_page_id')
        self.status_page_id = attributes[:'status_page_id']
      else
        self.status_page_id = nil
      end

      if attributes.key?(:'updates')
        if (value = attributes[:'updates']).is_a?(Array)
          self.updates = value
        end
      else
        self.updates = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @component_impacts.nil?
        invalid_properties.push('invalid value for "component_impacts", component_impacts cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @incident_status.nil?
        invalid_properties.push('invalid value for "incident_status", incident_status cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @published_at.nil?
        invalid_properties.push('invalid value for "published_at", published_at cannot be nil.')
      end

      if @status_page_id.nil?
        invalid_properties.push('invalid value for "status_page_id", status_page_id cannot be nil.')
      end

      if @updates.nil?
        invalid_properties.push('invalid value for "updates", updates cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @component_impacts.nil?
      return false if @id.nil?
      return false if @incident_status.nil?
      return false if @name.nil?
      return false if @published_at.nil?
      return false if @status_page_id.nil?
      return false if @updates.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] component_impacts Value to be assigned
    def component_impacts=(component_impacts)
      if component_impacts.nil?
        fail ArgumentError, 'component_impacts cannot be nil'
      end

      @component_impacts = component_impacts
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] incident_status Value to be assigned
    def incident_status=(incident_status)
      if incident_status.nil?
        fail ArgumentError, 'incident_status cannot be nil'
      end

      @incident_status = incident_status
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] published_at Value to be assigned
    def published_at=(published_at)
      if published_at.nil?
        fail ArgumentError, 'published_at cannot be nil'
      end

      @published_at = published_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status_page_id Value to be assigned
    def status_page_id=(status_page_id)
      if status_page_id.nil?
        fail ArgumentError, 'status_page_id cannot be nil'
      end

      @status_page_id = status_page_id
    end

    # Custom attribute writer method with validation
    # @param [Object] updates Value to be assigned
    def updates=(updates)
      if updates.nil?
        fail ArgumentError, 'updates cannot be nil'
      end

      @updates = updates
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          component_impacts == o.component_impacts &&
          id == o.id &&
          incident_status == o.incident_status &&
          name == o.name &&
          published_at == o.published_at &&
          status_page_id == o.status_page_id &&
          updates == o.updates
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [component_impacts, id, incident_status, name, published_at, status_page_id, updates].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
