=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class WorkloadMinutesV2 < ApiModelBase
    # Total minutes the user spent on the incident
    attr_accessor :minutes_spent_on_incident

    # Minutes spent during the user's late hours
    attr_accessor :minutes_spent_on_incident_in_late_hours

    # Minutes spent during the user's sleeping hours
    attr_accessor :minutes_spent_on_incident_in_sleeping_hours

    # Minutes spent during the user's working hours
    attr_accessor :minutes_spent_on_incident_in_working_hours

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'minutes_spent_on_incident' => :'minutes_spent_on_incident',
        :'minutes_spent_on_incident_in_late_hours' => :'minutes_spent_on_incident_in_late_hours',
        :'minutes_spent_on_incident_in_sleeping_hours' => :'minutes_spent_on_incident_in_sleeping_hours',
        :'minutes_spent_on_incident_in_working_hours' => :'minutes_spent_on_incident_in_working_hours'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'minutes_spent_on_incident' => :'Float',
        :'minutes_spent_on_incident_in_late_hours' => :'Float',
        :'minutes_spent_on_incident_in_sleeping_hours' => :'Float',
        :'minutes_spent_on_incident_in_working_hours' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::WorkloadMinutesV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::WorkloadMinutesV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'minutes_spent_on_incident')
        self.minutes_spent_on_incident = attributes[:'minutes_spent_on_incident']
      else
        self.minutes_spent_on_incident = nil
      end

      if attributes.key?(:'minutes_spent_on_incident_in_late_hours')
        self.minutes_spent_on_incident_in_late_hours = attributes[:'minutes_spent_on_incident_in_late_hours']
      else
        self.minutes_spent_on_incident_in_late_hours = nil
      end

      if attributes.key?(:'minutes_spent_on_incident_in_sleeping_hours')
        self.minutes_spent_on_incident_in_sleeping_hours = attributes[:'minutes_spent_on_incident_in_sleeping_hours']
      else
        self.minutes_spent_on_incident_in_sleeping_hours = nil
      end

      if attributes.key?(:'minutes_spent_on_incident_in_working_hours')
        self.minutes_spent_on_incident_in_working_hours = attributes[:'minutes_spent_on_incident_in_working_hours']
      else
        self.minutes_spent_on_incident_in_working_hours = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @minutes_spent_on_incident.nil?
        invalid_properties.push('invalid value for "minutes_spent_on_incident", minutes_spent_on_incident cannot be nil.')
      end

      if @minutes_spent_on_incident_in_late_hours.nil?
        invalid_properties.push('invalid value for "minutes_spent_on_incident_in_late_hours", minutes_spent_on_incident_in_late_hours cannot be nil.')
      end

      if @minutes_spent_on_incident_in_sleeping_hours.nil?
        invalid_properties.push('invalid value for "minutes_spent_on_incident_in_sleeping_hours", minutes_spent_on_incident_in_sleeping_hours cannot be nil.')
      end

      if @minutes_spent_on_incident_in_working_hours.nil?
        invalid_properties.push('invalid value for "minutes_spent_on_incident_in_working_hours", minutes_spent_on_incident_in_working_hours cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @minutes_spent_on_incident.nil?
      return false if @minutes_spent_on_incident_in_late_hours.nil?
      return false if @minutes_spent_on_incident_in_sleeping_hours.nil?
      return false if @minutes_spent_on_incident_in_working_hours.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] minutes_spent_on_incident Value to be assigned
    def minutes_spent_on_incident=(minutes_spent_on_incident)
      if minutes_spent_on_incident.nil?
        fail ArgumentError, 'minutes_spent_on_incident cannot be nil'
      end

      @minutes_spent_on_incident = minutes_spent_on_incident
    end

    # Custom attribute writer method with validation
    # @param [Object] minutes_spent_on_incident_in_late_hours Value to be assigned
    def minutes_spent_on_incident_in_late_hours=(minutes_spent_on_incident_in_late_hours)
      if minutes_spent_on_incident_in_late_hours.nil?
        fail ArgumentError, 'minutes_spent_on_incident_in_late_hours cannot be nil'
      end

      @minutes_spent_on_incident_in_late_hours = minutes_spent_on_incident_in_late_hours
    end

    # Custom attribute writer method with validation
    # @param [Object] minutes_spent_on_incident_in_sleeping_hours Value to be assigned
    def minutes_spent_on_incident_in_sleeping_hours=(minutes_spent_on_incident_in_sleeping_hours)
      if minutes_spent_on_incident_in_sleeping_hours.nil?
        fail ArgumentError, 'minutes_spent_on_incident_in_sleeping_hours cannot be nil'
      end

      @minutes_spent_on_incident_in_sleeping_hours = minutes_spent_on_incident_in_sleeping_hours
    end

    # Custom attribute writer method with validation
    # @param [Object] minutes_spent_on_incident_in_working_hours Value to be assigned
    def minutes_spent_on_incident_in_working_hours=(minutes_spent_on_incident_in_working_hours)
      if minutes_spent_on_incident_in_working_hours.nil?
        fail ArgumentError, 'minutes_spent_on_incident_in_working_hours cannot be nil'
      end

      @minutes_spent_on_incident_in_working_hours = minutes_spent_on_incident_in_working_hours
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          minutes_spent_on_incident == o.minutes_spent_on_incident &&
          minutes_spent_on_incident_in_late_hours == o.minutes_spent_on_incident_in_late_hours &&
          minutes_spent_on_incident_in_sleeping_hours == o.minutes_spent_on_incident_in_sleeping_hours &&
          minutes_spent_on_incident_in_working_hours == o.minutes_spent_on_incident_in_working_hours
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [minutes_spent_on_incident, minutes_spent_on_incident_in_late_hours, minutes_spent_on_incident_in_sleeping_hours, minutes_spent_on_incident_in_working_hours].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
