=begin
#incident.io

#Ruby client for the incident.io API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module IncidentIo
  class WorkflowsCreateWorkflowPayloadV2 < ApiModelBase
    # Annotations that track metadata about this resource
    attr_accessor :annotations

    # Whether the workflow runs immediately, or asks for confirmation in the incident channel first. Defaults to `run_automatically` on create. If omitted on update, the workflow keeps its current mode.  Known values: `run_automatically`, `confirm_before_running`
    attr_accessor :auto_run_mode

    # Conditions that apply to the workflow trigger
    attr_accessor :condition_groups

    # Whether to continue executing the workflow if a step fails
    attr_accessor :continue_on_step_error

    attr_accessor :delay

    # The expressions to use in the workflow
    attr_accessor :expressions

    # Folder to display the workflow in
    attr_accessor :folder

    # User-configured form fields available in the workflow scope. Allowed on manually-triggered workflows, and on workflows with an `auto_run_mode` of `confirm_before_running`.
    attr_accessor :form_fields

    # Whether to include private escalations
    attr_accessor :include_private_escalations

    # DEPRECATED: use `private_incident_scope` instead. May be sent alongside `private_incident_scope` only if they agree; contradictory values return a validation error.
    attr_accessor :include_private_incidents

    # Name provided by the user when creating the workflow
    attr_accessor :name

    # This workflow will run 'once for' a list of references
    attr_accessor :once_for

    # IDs of the teams that own this workflow
    attr_accessor :owning_team_ids

    # Which private incidents this workflow acts on: every private incident (all), those an owning team can see (owning_teams), or none  Known values: `all`, `owning_teams`, `none`
    attr_accessor :private_incident_scope

    # Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
    attr_accessor :runs_on_incident_modes

    # Which incidents should the workflow be applied to?  Known values: `newly_created`, `newly_created_and_active`
    attr_accessor :runs_on_incidents

    # The shortform used to trigger this workflow (only applicable for manual triggers)
    attr_accessor :shortform

    # What state this workflow is in  Known values: `active`, `disabled`, `draft`, `error`
    attr_accessor :state

    # Steps that are executed as part of the workflow
    attr_accessor :steps

    # Trigger to set on the workflow
    attr_accessor :trigger

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'annotations' => :'annotations',
        :'auto_run_mode' => :'auto_run_mode',
        :'condition_groups' => :'condition_groups',
        :'continue_on_step_error' => :'continue_on_step_error',
        :'delay' => :'delay',
        :'expressions' => :'expressions',
        :'folder' => :'folder',
        :'form_fields' => :'form_fields',
        :'include_private_escalations' => :'include_private_escalations',
        :'include_private_incidents' => :'include_private_incidents',
        :'name' => :'name',
        :'once_for' => :'once_for',
        :'owning_team_ids' => :'owning_team_ids',
        :'private_incident_scope' => :'private_incident_scope',
        :'runs_on_incident_modes' => :'runs_on_incident_modes',
        :'runs_on_incidents' => :'runs_on_incidents',
        :'shortform' => :'shortform',
        :'state' => :'state',
        :'steps' => :'steps',
        :'trigger' => :'trigger'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'annotations' => :'Hash<String, String>',
        :'auto_run_mode' => :'String',
        :'condition_groups' => :'Array<ConditionGroupPayloadV2>',
        :'continue_on_step_error' => :'Boolean',
        :'delay' => :'WorkflowDelayV2',
        :'expressions' => :'Array<ExpressionPayloadV2>',
        :'folder' => :'String',
        :'form_fields' => :'Array<WorkflowFormFieldPayloadV2>',
        :'include_private_escalations' => :'Boolean',
        :'include_private_incidents' => :'Boolean',
        :'name' => :'String',
        :'once_for' => :'Array<String>',
        :'owning_team_ids' => :'Array<String>',
        :'private_incident_scope' => :'String',
        :'runs_on_incident_modes' => :'Array<String>',
        :'runs_on_incidents' => :'String',
        :'shortform' => :'String',
        :'state' => :'String',
        :'steps' => :'Array<StepConfigPayloadV2>',
        :'trigger' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IncidentIo::WorkflowsCreateWorkflowPayloadV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IncidentIo::WorkflowsCreateWorkflowPayloadV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'annotations')
        if (value = attributes[:'annotations']).is_a?(Hash)
          self.annotations = value
        end
      end

      if attributes.key?(:'auto_run_mode')
        self.auto_run_mode = attributes[:'auto_run_mode']
      end

      if attributes.key?(:'condition_groups')
        if (value = attributes[:'condition_groups']).is_a?(Array)
          self.condition_groups = value
        end
      else
        self.condition_groups = nil
      end

      if attributes.key?(:'continue_on_step_error')
        self.continue_on_step_error = attributes[:'continue_on_step_error']
      else
        self.continue_on_step_error = nil
      end

      if attributes.key?(:'delay')
        self.delay = attributes[:'delay']
      end

      if attributes.key?(:'expressions')
        if (value = attributes[:'expressions']).is_a?(Array)
          self.expressions = value
        end
      else
        self.expressions = nil
      end

      if attributes.key?(:'folder')
        self.folder = attributes[:'folder']
      end

      if attributes.key?(:'form_fields')
        if (value = attributes[:'form_fields']).is_a?(Array)
          self.form_fields = value
        end
      end

      if attributes.key?(:'include_private_escalations')
        self.include_private_escalations = attributes[:'include_private_escalations']
      end

      if attributes.key?(:'include_private_incidents')
        self.include_private_incidents = attributes[:'include_private_incidents']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'once_for')
        if (value = attributes[:'once_for']).is_a?(Array)
          self.once_for = value
        end
      else
        self.once_for = nil
      end

      if attributes.key?(:'owning_team_ids')
        if (value = attributes[:'owning_team_ids']).is_a?(Array)
          self.owning_team_ids = value
        end
      end

      if attributes.key?(:'private_incident_scope')
        self.private_incident_scope = attributes[:'private_incident_scope']
      end

      if attributes.key?(:'runs_on_incident_modes')
        if (value = attributes[:'runs_on_incident_modes']).is_a?(Array)
          self.runs_on_incident_modes = value
        end
      else
        self.runs_on_incident_modes = nil
      end

      if attributes.key?(:'runs_on_incidents')
        self.runs_on_incidents = attributes[:'runs_on_incidents']
      else
        self.runs_on_incidents = nil
      end

      if attributes.key?(:'shortform')
        self.shortform = attributes[:'shortform']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'steps')
        if (value = attributes[:'steps']).is_a?(Array)
          self.steps = value
        end
      else
        self.steps = nil
      end

      if attributes.key?(:'trigger')
        self.trigger = attributes[:'trigger']
      else
        self.trigger = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @condition_groups.nil?
        invalid_properties.push('invalid value for "condition_groups", condition_groups cannot be nil.')
      end

      if @continue_on_step_error.nil?
        invalid_properties.push('invalid value for "continue_on_step_error", continue_on_step_error cannot be nil.')
      end

      if @expressions.nil?
        invalid_properties.push('invalid value for "expressions", expressions cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @once_for.nil?
        invalid_properties.push('invalid value for "once_for", once_for cannot be nil.')
      end

      if @runs_on_incident_modes.nil?
        invalid_properties.push('invalid value for "runs_on_incident_modes", runs_on_incident_modes cannot be nil.')
      end

      if @runs_on_incidents.nil?
        invalid_properties.push('invalid value for "runs_on_incidents", runs_on_incidents cannot be nil.')
      end

      if @steps.nil?
        invalid_properties.push('invalid value for "steps", steps cannot be nil.')
      end

      if @trigger.nil?
        invalid_properties.push('invalid value for "trigger", trigger cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @condition_groups.nil?
      return false if @continue_on_step_error.nil?
      return false if @expressions.nil?
      return false if @name.nil?
      return false if @once_for.nil?
      return false if @runs_on_incident_modes.nil?
      return false if @runs_on_incidents.nil?
      return false if @steps.nil?
      return false if @trigger.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] condition_groups Value to be assigned
    def condition_groups=(condition_groups)
      if condition_groups.nil?
        fail ArgumentError, 'condition_groups cannot be nil'
      end

      @condition_groups = condition_groups
    end

    # Custom attribute writer method with validation
    # @param [Object] continue_on_step_error Value to be assigned
    def continue_on_step_error=(continue_on_step_error)
      if continue_on_step_error.nil?
        fail ArgumentError, 'continue_on_step_error cannot be nil'
      end

      @continue_on_step_error = continue_on_step_error
    end

    # Custom attribute writer method with validation
    # @param [Object] expressions Value to be assigned
    def expressions=(expressions)
      if expressions.nil?
        fail ArgumentError, 'expressions cannot be nil'
      end

      @expressions = expressions
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] once_for Value to be assigned
    def once_for=(once_for)
      if once_for.nil?
        fail ArgumentError, 'once_for cannot be nil'
      end

      @once_for = once_for
    end

    # Custom attribute writer method with validation
    # @param [Object] runs_on_incident_modes Value to be assigned
    def runs_on_incident_modes=(runs_on_incident_modes)
      if runs_on_incident_modes.nil?
        fail ArgumentError, 'runs_on_incident_modes cannot be nil'
      end

      @runs_on_incident_modes = runs_on_incident_modes
    end

    # Custom attribute writer method with validation
    # @param [Object] runs_on_incidents Value to be assigned
    def runs_on_incidents=(runs_on_incidents)
      if runs_on_incidents.nil?
        fail ArgumentError, 'runs_on_incidents cannot be nil'
      end

      @runs_on_incidents = runs_on_incidents
    end

    # Custom attribute writer method with validation
    # @param [Object] steps Value to be assigned
    def steps=(steps)
      if steps.nil?
        fail ArgumentError, 'steps cannot be nil'
      end

      @steps = steps
    end

    # Custom attribute writer method with validation
    # @param [Object] trigger Value to be assigned
    def trigger=(trigger)
      if trigger.nil?
        fail ArgumentError, 'trigger cannot be nil'
      end

      @trigger = trigger
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          annotations == o.annotations &&
          auto_run_mode == o.auto_run_mode &&
          condition_groups == o.condition_groups &&
          continue_on_step_error == o.continue_on_step_error &&
          delay == o.delay &&
          expressions == o.expressions &&
          folder == o.folder &&
          form_fields == o.form_fields &&
          include_private_escalations == o.include_private_escalations &&
          include_private_incidents == o.include_private_incidents &&
          name == o.name &&
          once_for == o.once_for &&
          owning_team_ids == o.owning_team_ids &&
          private_incident_scope == o.private_incident_scope &&
          runs_on_incident_modes == o.runs_on_incident_modes &&
          runs_on_incidents == o.runs_on_incidents &&
          shortform == o.shortform &&
          state == o.state &&
          steps == o.steps &&
          trigger == o.trigger
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [annotations, auto_run_mode, condition_groups, continue_on_step_error, delay, expressions, folder, form_fields, include_private_escalations, include_private_incidents, name, once_for, owning_team_ids, private_incident_scope, runs_on_incident_modes, runs_on_incidents, shortform, state, steps, trigger].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
